stages:
  - deploy

variables:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: secret

deploy:
  stage: deploy
  image: docker:latest
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login hub.laberit.com -u "$CI_REGISTRY_USER" --password-stdin
    - docker-compose up -d myapp
  tags:
    - bootcamp
  only:
    - main